version: "2"
run:
  issues-exit-code: 1
linters:
  enable:
    - asciicheck
    - bodyclose
    - errorlint
    - gocritic
    - gosec
    - importas
    - misspell
    - prealloc
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        path: pkg/ctlog/config.go
        text: SA1019
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
